services:
  api:
    build: ./app
    container_name: 02-facility-api
    ports:
      - "3002:3000"
    environment:
      - MONGO_URI=mongodb://db:27017/02-facility
    depends_on:
      db:
        condition: service_healthy
    networks:
      - enterprise-net
  db:
    image: mongo:6
    container_name: 02-facility-db
    networks:
      - enterprise-net
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
networks:
  enterprise-net:
    external: true
