version: '3.8'
services:
  api:
    build: ./app
    container_name: 03-inventory-api-1
    ports:
      - "3003:3000"
    environment:
      - MONGO_URI=mongodb://db:27017/03-inventory
    depends_on:
      db:
        condition: service_healthy
    networks:
      - enterprise-net
  db:
    image: mongo:6
    container_name: 03-inventory-db-1
    networks:
      - enterprise-net
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
networks:
  enterprise-net:
    external: true
